{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule | quote }}
  timeZone: "Europe/Berlin"
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: cloudflare-dyndns
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
          containers:
            - name: app
              image: "{{ $.Values.image.name }}:{{ $.Values.appVersion }}"
              command:
                - "tini"
                - "--"
                - "uv"
                - "run"
                - "-m"
                - "cloudflare_dyndns.cli"
              args:
                - {{ .name }}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ ALL ]
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: "1"
              envFrom:
                - configMapRef:
                    name: config
                - secretRef:
                    name: tokens
{{- end }}
