apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    {{- with .Values.ingress.certificate }}
    cert-manager.io/cluster-issuer: {{ .issuer }}
    cert-manager.io/private-key-algorithm: {{ .algorithm }}
    cert-manager.io/private-key-rotation-policy: Always
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  name: http
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: api-cert
