---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tokens
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-born-cloudflare-dyndns
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: "name:sentry-dsn"
      secretKey: SENTRY_DSN
    - remoteRef:
        key: "name:cloudflare-token"
      secretKey: CLOUDFLARE_TOKEN
  dataFrom:
    - extract:
        key: "name:manual-secrets"
