---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-prep-update-receiver
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: "name:sentry-dsn"
      secretKey: SENTRY_DSN
    - remoteRef:
        key: "name:update-receiver-token"
      secretKey: SECRET_TOKEN
